version: "2.0"

# Authors: harry.kodden@surf.nl
#          gerben.venekamp@surf.nl
#
# Starting a local LDAP:
#
#   $ docker-compose up -d ldap
#
# Starting an example SRAM like ldap on port 388:
#
#   $ docker-compose up -d ldap-sram
#
# Optionally start LDAPphpAdmin:
#
#   $ docker-compose up -d ldapadmin
#

services:
  ldap:
    image: osixia/openldap:latest
    environment:
      LDAP_LOG_LEVEL: 0
      LDAP_BACKEND: ${DST_LDAP_BACKEND}
      LDAP_ORGANISATION: SURF
      LDAP_DOMAIN: ${DST_LDAP_DOMAIN}
      LDAP_CONFIG_PASSWORD: ${DST_LDAP_PASSWD}
      LDAP_ADMIN_PASSWORD: ${DST_LDAP_PASSWD}
      LDAP_BASE_DN: ${DST_LDAP_BASEDN}
      LDAP_TLS: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      DISABLE_CHOWN: "true"
    ports:
      - 389:389
    volumes:
      - "${PWD}/config/dest/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom"
    command: --copy-service --loglevel debug

  ldap-sram:
    image: osixia/openldap:latest
    environment:
      LDAP_LOG_LEVEL: 0x0000
      LDAP_BACKEND: ${DST_LDAP_BACKEND}
      LDAP_ORGANISATION: SURF
      LDAP_DOMAIN: ${DST_LDAP2_DOMAIN}
      LDAP_CONFIG_PASSWORD: ${DST_LDAP2_PASSWD}
      LDAP_ADMIN_PASSWORD: ${DST_LDAP2_PASSWD}
      LDAP_BASE_DN: ${DST_LDAP2_BASEDN}
      LDAP_TLS: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      DISABLE_CHOWN: "true"
    ports:
      - 388:389
    volumes:
      - "${PWD}/config/src/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom"
    command: --copy-service --loglevel debug

  ldapadmin:
    image: osixia/phpldapadmin:latest
    links:
      - ldap
    depends_on:
      - ldap
    ports:
      - 8888:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_SERVER_PATH: "/"
      PHPLDAPADMIN_SERVER_ADMIN: "admin"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
    restart: always
    command: --loglevel debug
