#!/usr/bin/env bash

CONFIG_DIR="config.d"


# Set the python virtual environment
. ${PWD}/venv/bin/activate

cd ${CONFIG_DIR}

for service in *; do
    $service/sync_services $service/$service.yml
    $service/plsc $service/$service.yml
    $service/plsc $service/$service.yml
done
